### ISSUE TITLE
Add Project Directory Outlines

### ISSUE THREAD

**Issue by bama4** [Rohanvamshi/Dark_bulb#16]
**Description**
This issue involves adding a bare project structure to the master branch
The structure of the project is as follows:
```
dev_gpio
    |_____________   Makefile
    |_____________   src
                     |_____________ dev_gpio.c

    |_____________   include
                     |_____________ dev_gpio.h
                   
bulb
    |_____________   Makefile 
    |_____________   src
                      |_____________ bulb.c
    |_____________   include
                      |_____________ bulb.h  
Makefile
scripts
    |_____________   install.sh
man
    |_____________   bulb.man
```

**Prerequisites**
Design documents are done

**Goal**
This ticket requires the following:
- [X] Create stubbed out project, files can be empty

**Definition of Done**
This ticket is completed when this is merged into master

**Comment by bama4** [comment]
@Rohanvamshi The include header files that you put in:

```
    |_____________   include
                     |_____________ linux/kernel.h
                     |_____________ linux/module.h
                     |_____________ sys/ioctl.h
```
Are system header files and we won't have to explicitly place them in our project directory.

Also I see that I accidentally placed bulb.h in a `src` directory (oops 😆)  but `.h` files should be in their appropriate `include` directories.

**Comment by Rohanvamshi** [comment]
@bama4 Dint know they were system headers. Missed that point. Made the changes. Check and revert if any more changes need to be done.
