### ISSUE TITLE
Add  function for module_init in GPIO_Device_Driver.c

### ISSUE THREAD

**Issue by Rohanvamshi** [Rohanvamshi/Dark_bulb#17]
**Description**
This issue involves creating the function in GPIO_Device_Driver.c for initializing the kernel module

**Goal**
This ticket requires the following:
- [x] Create a function to print an alert message to the kernel system log when GPIO_Device_Driver.ko (kernel object)  is added to the kernel
- [x] Make sure return is non-zero if device fails to register in dev_gpio_init
- [x] Make sure that module correctly loads in kernel

Edit: module_exit #18 is included in this issue
**Prerequisites**
None

**Definition of Done**
This ticket is completed when the function is implemented in GPIO_Device_Driver.c and tested

**Comment by bama4** [comment]
This is good thinking, we def want some type of confirmation messages.

You should be able to print the initialization message by calling `printk`  in the function that is passed to `module_init` in your kernel module source code.
This ticket may be better off being one of several steps in a single ticket to write the `module_init` function for the kernel module

**Comment by Rohanvamshi** [comment]
Title seems to be a little misleading. I wanted it to be a ticket for module_init as well. Will make the changes soon 👍
