### ISSUE TITLE
Add function for module_exit in GPIO_Device_Driver.c

### ISSUE THREAD

**Issue by Rohanvamshi** [Rohanvamshi/Dark_bulb#18]
**Description**
This issue involves creating the function in GPIO_Device_Driver.c for printing a cleanup confirmation message when the kernel module is removed from the kernel space. 

**Goal**
This ticket requires the following:
- [x] Create a function to print an alert message to the kernel system log when GPIO_Device_Driver.ko (kernel object)  is removed from the kernel

Edit: This is included in #17 
**Prerequisites**
Initialization function of GPIO_Device_driver.c is implemented and tested.

**Definition of Done**
This ticket is completed when the function is implemented in GPIO_Device_Driver.c and tested

**Comment by bama4** [comment]
As I mentioned in #17 , since we can print messages using `printk` this may be better lumped with the ticket that implements the cleanup function passed to `module_exit`

**Comment by bama4** [comment]
Had to do module init and exit at the same time to test that the device properly was created and removed
