### ISSUE TITLE
Add function to print open confirmation message for GPIO_Device_Driver.c

### ISSUE THREAD

**Issue by Rohanvamshi** [Rohanvamshi/Dark_bulb#19]
**Description**
This issue involves creating the function in GPIO_Device_Driver.c for printing an open confirmation message when the kernel module is opened.

**Goal**
This ticket requires the following:
- [x] Create a function to print an alert message to the kernel system log when GPIO_Device_Driver.ko (kernel object)  is opened.

**Prerequisites**
Initialization and cleanup functions for GPIO_Device_driver.c is implemented and tested.

**Definition of Done**
This ticket is completed when the function is implemented in GPIO_Device_Driver.c and tested

**Comment by bama4** [comment]
Link about implementing open and release: https://www.oreilly.com/library/view/linux-device-drivers/0596000081/ch03s05.html
