### ISSUE TITLE
Design /dev/gpio Device Driver

### ISSUE THREAD

**Issue by bama4** [Rohanvamshi/Dark_bulb#2]
**Description**
This is only for designing the GPIO device driver. Implementation is in a separate ticket.
The design details can go here: [GPIO Device Driver Design](https://docs.google.com/document/d/11L2q3n9vHTHyTzZiKzas5QcR-JndBtZULnVz5ncvkqI/edit?usp=sharing)

**Prerequisites**

**Goal**
This ticket requires the following:

- [x] Describe functions for device driver that can be translated into tickets.
- [x] Designing how to send and receive commands by the device driver 
- [x] Designing how to configure specific pins and create a state diagram of how gpio device driver will interact with hardware I/O 

**Definition of Done**
This ticket is completed when the following is done:

**Comment by Rohanvamshi** [comment]
Communication between the device driver and the user space program.  
Initial reference: http://www.cs.otago.ac.nz/cosc440/labs/lab06.pdf

**Comment by Rohanvamshi** [comment]
Design of UML diagram on how device driver will interact with Rpi hardware in [layout](https://docs.google.com/document/d/11L2q3n9vHTHyTzZiKzas5QcR-JndBtZULnVz5ncvkqI/edit#)
